version: '3'
services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 42384942     
    volumes:      #para persistencia de datos
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  # Servicio de la aplicación Node.js
  node_app:
    image: enzo23/appcrud 
    container_name: mi_app_node
    ports:
      - "3000:3000"    
    depends_on: #hace referencia a mysql
      - mysql
    networks:  #nombre de red para que puedan interconectarse
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
